Repository TeamNado-Sunbae/NadoSunbae-iOS, pull requests merged in 2022-10, with the labels that each got.

#480 ✨ [FEAT] 게시글 작성 API를 연결합니다.
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Class/WritePost/BaseWritePostVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/PublicAPI.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Public/WritePostReqModel.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Public/WritePostResModel.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/PublicService.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/DefaultQuestionChatVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/WriteQuestionVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Community/Reactor/CommunityWriteReactor.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Community/VC/CommunityMainVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Community/VC/CommunityWriteVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC.swift
  NadoSunbae-iOS/NadoSunbae.xcodeproj/project.pbxproj
Labels: 📡 Network, 🍎 Feature, 💡 Refactor, ✨🍕 Jieun 🐰✨, ✏️ 과방탭, 🍉 커뮤니티탭

#490 ✨ [FEAT] 홈 탭 화면전환 연결 및 후기 상세 뷰 UI 수정사항 반영
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Public/ContentListData.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Review/ReviewEditData.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Review/ReviewPostDetailData.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Review/ReviewPostRegisterData.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/ReviewService.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/VC/RankingVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/VC/RecentReviewVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewDetailGrayTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewDetailGrayTVC.xib
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewDetailPostTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewDetailPostTVC.xib
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewDetailPostWithImgTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewDetailPostWithImgTVC.xib
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewDetailProfileTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewDetailProfileTVC.xib
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewDetailVC.swift
  NadoSunbae-iOS/NadoSunbae.xcodeproj/project.pbxproj
  NadoSunbae-iOS/NadoSunbae.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: 📱 View, 🍎 Feature, 💜 은주 💜, ✅ Chore, 📰 홈 탭

#497 ♻️ [REFACTOR] NadoSegmentedContol 공용 컴포넌트 UI 구현부를 리펙토링합니다.
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Extension/UIColor+.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Class/NadoSegmentedControl.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/Review/ClassroomMainHeaderView.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Community/VC/CommunityMainVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/LikeList/MypageLikeListVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypagePostList/VC/MypagePostListVC.swift
Labels: 📱 View, 💡 Refactor, ✨🍕 Jieun 🐰✨

#500 ✨ [FEAT] 홈 뷰 -> 선배랭킹의 선배 클릭 시 해당 선배페이지로 이동
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Protocol/SendRankerDataDelegate.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/TVC/HomeRankingTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/VC/HomeVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/View/HomeRankerView.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC+TV.swift
  NadoSunbae-iOS/NadoSunbae.xcodeproj/project.pbxproj
Labels: 📱 View, 🍎 Feature, ❤️ 정빈걸 ❤️, 📰 홈 탭

#505 🔨 [FIX] 마이페이지 QA 수정
  NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Class/NadoEmptyView.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/LikeList/MypageLikeListVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypagePostList/VC/MypagePostListVC.swift
  NadoSunbae-iOS/NadoSunbae.xcodeproj/project.pbxproj
Labels: 🐞 Bug, ❤️ 정빈걸 ❤️, 🙋🏻‍♀️ 마이페이지탭, 🛠 QA

#511 🔨 [FIX] 회원가입 QA 수정
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignUp/SignUpMajorInfo/VC/SignUpModalVC.swift
Labels: 🐞 Bug, ❤️ 정빈걸 ❤️, 🛠 QA

#510 ♻️ [REFACTOR] 과방탭 - 후기/1:1질문 통합 메인뷰 UI 구조를 리펙토링합니다.
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Extension/UIColor+.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Protocol/SendContentSizeDelegate.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/ClassroomAPI.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Classroom/Question/MajorUserListDataModel.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/ClassroomService.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/QuestionMain/AvailableQuestionPersonTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Reactor/ClassroomReactor.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Reactor/PersonalQuestionReactor.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/ClassroomNC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/ClassroomVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/PersonalQuestionVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/QuestionMainVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/QuestionPersonListVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/ReviewVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/reviewFloatingBtn.imageset/Contents.json
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/reviewFloatingBtn.imageset/reviewFloatingBtn.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/reviewFloatingBtn.imageset/reviewFloatingBtn@2x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/reviewFloatingBtn.imageset/reviewFloatingBtn@3x.png
  NadoSunbae-iOS/NadoSunbae.xcodeproj/project.pbxproj
Labels: 📱 View, 🍎 Feature, 💡 Refactor, ✨🍕 Jieun 🐰✨, ✏️ 과방탭

#513 🔨 [FIX] 커뮤니티 글 리스트 행간 조정하기
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Community/Cell/TVC/CommunityTVC.swift
Labels: ⚡️ HotFix, ✨🍕 Jieun 🐰✨, 🍉 커뮤니티탭

#515 🔨 [FIX] 커뮤니티 글 리스트 클릭 후 뒤로 돌아왔을 때 전체 글로 reload 되는 버그 해결하기
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Struct/PostFilterType.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Community/VC/CommunityMainVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Community/VC/CommunityWriteVC.swift
Labels: 🐞 Bug, ⚡️ HotFix, ✨🍕 Jieun 🐰✨, 🍉 커뮤니티탭

#517 🔨 [FIX] 게시글 수정 카테고리 회색 처리 미반영되는 문제 해결
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Community/Cell/CVC/CommunityWriteCategoryCVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Community/VC/CommunityWriteVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/Community/RadioButtonDark.imageset/Contents.json
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/Community/RadioButtonDark.imageset/RadioButtonDark.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/Community/RadioButtonDark.imageset/RadioButtonDark@2x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/Community/RadioButtonDark.imageset/RadioButtonDark@3x.png
Labels: 🐞 Bug, ⚡️ HotFix, ✨🍕 Jieun 🐰✨, 🍉 커뮤니티탭

#523 🔨 [FIX] 삭제된 댓글에 대해서 삭제 기능 다시 가능한 문제 해결하기
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Community/Cell/TVC/PostDetail/InfoCommentTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Community/Cell/TVC/PostDetail/InfoCommentTVC.xib
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Community/VC/CommunityPostDetailVC.swift
Labels: 🐞 Bug, ⚡️ HotFix, ✨🍕 Jieun 🐰✨, 🍉 커뮤니티탭

#525 🔨 [FIX] 회원가입 QA 수정
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/SignAPI.swift
Labels: 🐞 Bug, ❤️ 정빈걸 ❤️, 🛠 QA

#527 ✅ [CHORE] 마이페이지 emptyView UX Writing 수정
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/LikeList/MypageLikeListVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypagePostList/VC/MypagePostListVC.swift
Labels: ❤️ 정빈걸 ❤️, 🙋🏻‍♀️ 마이페이지탭, ✅ Chore

#529 ✅ [CHORE] NadoAlert UI 수정
  NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Class/NadoAlertVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Xib/NadoAlertVC.xib
Labels: 📱 View, ❤️ 정빈걸 ❤️, ✅ Chore

#531 🔨 [FIX] 런치스크린 UI 기기대응
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/SB/SignInSB.storyboard
Labels: 📱 View, ❤️ 정빈걸 ❤️, ✅ Chore

#535 ✨ [FEAT] 업데이트 알럿 기능 추가
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Class/BaseVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/MypageSettingService.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/VC/HomeVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewMainVC.swift
Labels: 🍎 Feature, ❤️ 정빈걸 ❤️, 📰 홈 탭

#537 🔨 [FIX] 마이페이지 내가 쓴 답글 1:1 질문 model 수정
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Mypage/MypageMyAnswerListModel.swift
Labels: 🐞 Bug, ❤️ 정빈걸 ❤️, 🙋🏻‍♀️ 마이페이지탭, 🛠 QA

#539 ✅ [CHORE] 테이블뷰 마지막 셀 separator 숨김 처리
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Class/BaseTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Extension/UITableView+.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Extension/UIView+.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/VC/HomeRecentPersonalQuestionVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypagePostList/VC/MypagePostListVC.swift
Labels: 📱 View, ❤️ 정빈걸 ❤️, 🙋🏻‍♀️ 마이페이지탭, ✅ Chore, 📰 홈 탭

#532 ✨ [FEAT] 프로필 수정 뷰 수정사항 반영
  NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Xib/HalfModalVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Xib/MajorTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Community/VC/CommunityWriteVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ProfileSetting/SB/EditProfileVC.storyboard
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ProfileSetting/VC/EditProfileImgModalVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ProfileSetting/VC/EditProfileVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/HalfModalPresentationController.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/ProfileImage/Frame 920.imageset/Contents.json
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/ProfileImage/Frame 920.imageset/Frame 920.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/ProfileImage/Frame 920.imageset/Frame 920@2x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/ProfileImage/Frame 920.imageset/Frame 920@3x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/ProfileImage/Frame 921.imageset/Contents.json
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/ProfileImage/Frame 921.imageset/Frame 921.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/ProfileImage/Frame 921.imageset/Frame 921@2x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/ProfileImage/Frame 921.imageset/Frame 921@3x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/ProfileImage/Frame 922.imageset/Contents.json
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/ProfileImage/Frame 922.imageset/Frame 922.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/ProfileImage/Frame 922.imageset/Frame 922@2x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/ProfileImage/Frame 922.imageset/Frame 922@3x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/ProfileImage/Frame 923.imageset/Contents.json
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/ProfileImage/Frame 923.imageset/Frame 923.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/ProfileImage/Frame 923.imageset/Frame 923@2x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/ProfileImage/Frame 923.imageset/Frame 923@3x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/ProfileImage/Frame 924.imageset/Contents.json
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/ProfileImage/Frame 924.imageset/Frame 924.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/ProfileImage/Frame 924.imageset/Frame 924@2x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/ProfileImage/Frame 924.imageset/Frame 924@3x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/ProfileImage/icon_check_img.imageset/Contents.json
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/ProfileImage/icon_check_img.imageset/icon_check_img.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/ProfileImage/icon_check_img.imageset/icon_check_img@2x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/ProfileImage/icon_check_img.imageset/icon_check_img@3x.png
  NadoSunbae-iOS/NadoSunbae.xcodeproj/project.pbxproj
Labels: 📱 View, 🍎 Feature, 💜 은주 💜, 🙋🏻‍♀️ 마이페이지탭, ✅ Chore

#540 ✨ [FEAT] 과방 질문가능선배뷰 UI 변경사항 적용 & 서버통신 코드 수정
  NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Class/NadoSwitch.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/ClassroomAPI.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/ClassroomService.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/CVC/QuestionPeopleHeaderView.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/CVC/QuestionPeopleHeaderView.xib
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Reactor/PersonalQuestionReactor.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/QuestionPersonListVC.swift
  NadoSunbae-iOS/NadoSunbae.xcodeproj/project.pbxproj
Labels: 📡 Network, 📱 View, 🍎 Feature, 💡 Refactor, ✨🍕 Jieun 🐰✨, ✏️ 과방탭

#546 ✨ [FEAT] 커뮤니티 메인뷰의 emptyView를 구현합니다.
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Community/VC/CommunityMainVC.swift
Labels: 📱 View, 🍎 Feature, ✨🍕 Jieun 🐰✨, 🍉 커뮤니티탭

#551 🔨 [FIX] 나의 1:1 질문에 대해서 이 선배에게 새 질문하기가 뜨는 문제 해결
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Public/GetUserPersonalQuestionListResponseData.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/MypageMainVC+TV.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC+TV.swift
Labels: ✨🍕 Jieun 🐰✨, 🙋🏻‍♀️ 마이페이지탭, 🛠 QA

#553 🔨 [FIX] 커뮤니티 글 삭제시 네트워크 오류가 발생하는 문제 해결
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/ClassroomAPI.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/PublicAPI.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/ClassroomService.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/PublicService.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/DefaultQuestionChatVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Community/VC/CommunityPostDetailVC.swift
  NadoSunbae-iOS/NadoSunbae.xcodeproj/project.pbxproj
Labels: ✨🍕 Jieun 🐰✨, 🛠 QA, 🍉 커뮤니티탭

#557 🔨 [QA] 커뮤니티 글 작성뷰에서 '질문’ 선택시 빠진 문구 추가하기
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Community/VC/CommunityWriteVC.swift
Labels: 📱 View, ✨🍕 Jieun 🐰✨, ✅ Chore, 🛠 QA

#565 ✨ [FEAT] 과방 후기 글 리스트 조회 및 화면전환 구현
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/ReviewAPI.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Classroom/ReviewPostModel.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Review/ReviewMainPostListData.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/ReviewService.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/Review/ClassroomMainHeaderView.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/Review/ReviewMainPostTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Reactor/ClassroomMainReactor.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Reactor/ClassroomMainSection.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Reactor/ReviewReactor.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/ClassroomMainVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/ClassroomVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/ReviewVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewMainVC.swift
  NadoSunbae-iOS/NadoSunbae.xcodeproj/project.pbxproj
Labels: 📡 Network, 📱 View, 💡 Refactor, 💜 은주 💜, ✏️ 과방탭, ✅ Chore

#572 ✨ [FEAT] 질문가능선배 리스트뷰 EmptyView 구현
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/CVC/AvailableQuestionPersonEmptyCVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/CVC/QuestionPersonEmptyLabelCVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/QuestionPersonListVC.swift
  NadoSunbae-iOS/NadoSunbae.xcodeproj/project.pbxproj
Labels: 📱 View, ✨🍕 Jieun 🐰✨, ✏️ 과방탭

#576 ✨ [FEAT] 과방 loading Indicator, error Alert 기능 추가
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Class/BaseVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Protocol/SendLoadingStatusDelegate.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Struct/AlertType.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/QuestionMain/RecentQuestionTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Reactor/PersonalQuestionReactor.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Reactor/RecentQuestionTVCReactor.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Reactor/ReviewReactor.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/ClassroomVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/PersonalQuestionVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/DefaultQuestionChatVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/QuestionPersonListVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/ReviewVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/WriteQuestionVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Community/VC/CommunityPostDetailVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/VC/HomeRecentPersonalQuestionVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/VC/HomeVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/LikeList/MypageLikeListVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/MypageMainVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypagePostList/VC/MypageMyReviewVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypagePostList/VC/MypagePostListVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ProfileSetting/VC/EditProfileVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ResetPW/VC/MailCompleteVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ResetPW/VC/ResetPWVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/Setting/VC/BlockListVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/Setting/VC/SettingVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Notification/VC/NotificationMainVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewMainLinkTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewDetailVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewMainVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewWriteVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/SignInVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignUp/SignUpMajorInfo/VC/SignUpModalVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignUp/SignUpUserInfo/VC/SignUpUserInfoVC.swift
  NadoSunbae-iOS/NadoSunbae.xcodeproj/project.pbxproj
Labels: ✨🍕 Jieun 🐰✨, ✏️ 과방탭, ✅ Chore

#584 ✅ [CHORE] 프로필 수정 뷰 정상화
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/MypageSettingAPI.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Mypage/MypageEditProfileRequestBodyModel.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Mypage/MypageSetting/EditProfileRequestModel.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/MypageSettingService.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ProfileSetting/VC/EditProfileVC.swift
  NadoSunbae-iOS/NadoSunbae.xcodeproj/project.pbxproj
Labels: ❤️ 정빈걸 ❤️, 🙋🏻‍♀️ 마이페이지탭, ✅ Chore, 🛠 QA

#586 🔨 [QA] 홈 - 커뮤니티, 최근 1:1 게시글 개수 제한 오류 수정
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/TVC/HomeRecentReviewQuestionTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/VC/HomeVC.swift
Labels: 🐞 Bug, ❤️ 정빈걸 ❤️, 🛠 QA, 📰 홈 탭

#587 🔨 [FIX] 알림 탭 Empty뷰 처리
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Notification/GetNotiListResponseData.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Notification/Cell/NotificationTVC.swift
Labels: ❤️ 정빈걸 ❤️, 🔔 알림탭, 🛠 QA

#589 🔨 [QA] 1:1질문 플로팅 버튼 띄우는 로직을 선배의 답변이 한개 이상일 때로 수정하기
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/DefaultQuestionChatVC.swift
Labels: ✨🍕 Jieun 🐰✨, ✏️ 과방탭, 🛠 QA

#590 🔨 [FIX] 선배 마이페이지 > 학과후기 "내가 쓴 후기" 수정
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypagePostList/VC/MypageMyReviewVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC.swift
Labels: 📱 View, ❤️ 정빈걸 ❤️, 🙋🏻‍♀️ 마이페이지탭, 🛠 QA

#593 🔨 [FIX] 과방 선배 리스트뷰 loading Indicator 보이지 않는 이슈 해결
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/QuestionPersonListVC.swift
Labels: 📱 View, ✨🍕 Jieun 🐰✨, ✏️ 과방탭, ✅ Chore

#598 ✨ [FEAT] 과방 탭 후기 필터 및 정렬 기능 구현
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Struct/ReviewWriterType.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/ReviewAPI.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Reactor/ReviewReactor.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/ClassroomVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/SB/ReviewDetailSB.storyboard
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/SB/ReviewSB.storyboard
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewMainVC.swift
  NadoSunbae-iOS/NadoSunbae.xcodeproj/project.pbxproj
Labels: 📡 Network, 🍎 Feature, 💜 은주 💜, ✏️ 과방탭

#601 🔨 [FIX] 홈-커뮤니티, 마이페이지 TableView Height 못 잡는 문제 수정
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/TVC/HomeCommunityTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/VC/HomeVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/LikeList/MypageLikeListVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypagePostList/VC/MypagePostListVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/SB/MypageUserVC.storyboard
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC+TV.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC.swift
Labels: 🐞 Bug, ❤️ 정빈걸 ❤️, 🙋🏻‍♀️ 마이페이지탭, ✅ Chore, 🛠 QA, 📰 홈 탭

#603 ✅ [CHORE] 차단한 유저 조회 정상화
  NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/MypageSettingService.swift
Labels: 📡 Network, ❤️ 정빈걸 ❤️, 🙋🏻‍♀️ 마이페이지탭

#610 🔨 [FIX] 커뮤니티 상세글) 전공정보 Label에서 본전공 제2전공 사이 행간 수정
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Community/Cell/TVC/PostDetail/InfoCommentTVC.swift
Labels: ✨🍕 Jieun 🐰✨, ✅ Chore, 🛠 QA, 🍉 커뮤니티탭

#613 ✨ [FEAT] 과방 후기 Empty 뷰 구현
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/ReviewVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/Reactor/RecentReviewReactor.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/VC/RecentReviewVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewEmptyTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewEmptyTVC.xib
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewMainLinkTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewMainLinkTVC.xib
  NadoSunbae-iOS/NadoSunbae.xcodeproj/project.pbxproj
Labels: 🐞 Bug, 📱 View, 🍎 Feature, 💜 은주 💜, ✏️ 과방탭, 📰 홈 탭

#615 🔨 [FIX] 홈 및 홈 이하 뷰 QA 반영
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Class/BaseVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Extension/Notification.Name.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/CVC/HomeRecentReviewQuestionCVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/TVC/HomeCommunityTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/TVC/HomeRankingTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/TVC/HomeRecentReviewQuestionTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/VC/HomeRecentPersonalQuestionVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/VC/HomeVC.swift
Labels: ❤️ 정빈걸 ❤️, 🛠 QA, 📰 홈 탭

#619 🔨 [FIX] 부적절 후기 작성자 최초 1회 알럿 뜬 후 후기 미작성자 권한으로 강등하도록 코드 수정
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Class/BaseVC.swift
Labels: ⚡️ HotFix, ✨🍕 Jieun 🐰✨, 🛠 QA

#620 ✅ [CHORE] 온보딩 이미지 수정
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Extension/UILabel+.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Onboarding/Cell/CVC/FirstOnboardingCVC.xib
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Onboarding/Cell/CVC/OnboardingCVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Onboarding/Cell/CVC/OnboardingCVC.xib
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Onboarding/Cell/CVC/ThirdOnboardingCVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Onboarding/Cell/CVC/ThirdOnboardingCVC.xib
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Onboarding/VC/OnboardingVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/Onboarding/Contents.json
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/Onboarding/onboarding1.imageset/Contents.json
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/Onboarding/onboarding1.imageset/onboarding1.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/Onboarding/onboarding1.imageset/onboarding1@2x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/Onboarding/onboarding1.imageset/onboarding1@3x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/Onboarding/onboarding2.imageset/Contents.json
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/Onboarding/onboarding2.imageset/onboarding2.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/Onboarding/onboarding2.imageset/onboarding2@2x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/Onboarding/onboarding2.imageset/onboarding2@3x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/Onboarding/onboarding3.imageset/Contents.json
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/Onboarding/onboarding3.imageset/onboarding3.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/Onboarding/onboarding3.imageset/onboarding3@2x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/Onboarding/onboarding3.imageset/onboarding3@3x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/Onboarding/onboardingFirstPage.imageset/Contents.json
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/Onboarding/onboardingFirstPage.imageset/onboardingFirstPage.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/Onboarding/onboardingFirstPage.imageset/onboardingFirstPage@2x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/Onboarding/onboardingFirstPage.imageset/onboardingFirstPage@3x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/group678.imageset/Contents.json
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/group678.imageset/group678.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/group678.imageset/group678@2x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/group678.imageset/group678@3x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/group687.imageset/Contents.json
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/group687.imageset/group687.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/group687.imageset/group687@2x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/group687.imageset/group687@3x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/lastPage.imageset/Contents.json
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/lastPage.imageset/lastPage.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/lastPage.imageset/lastPage@2x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/lastPage.imageset/lastPage@3x.png
  NadoSunbae-iOS/NadoSunbae.xcodeproj/project.pbxproj
Labels: 📱 View, 💜 은주 💜, ✅ Chore

#622 🔨 [QA] 마이페이지/선배페이지 프로필 사진 배경 수정
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/MypageMainVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC.swift
Labels: 📱 View, ❤️ 정빈걸 ❤️, 🙋🏻‍♀️ 마이페이지탭, 🛠 QA

#626 🔨 [FIX] 커뮤니티 학과 필터 설정 후 다른 탭으로 이동 후 다시 돌아오면 필터 기능 풀려있는 이슈 대응
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Community/Reactor/CommunityMainReactor.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Community/VC/CommunityMainVC.swift
Labels: ✨🍕 Jieun 🐰✨, 🛠 QA, 🍉 커뮤니티탭

#631 ✅ Chore: 설정 > 서비스 문의 및 건의로 변경 (#630)
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/Setting/SB/SettingVC.storyboard
Labels: 📱 View, ❤️ 정빈걸 ❤️, 🙋🏻‍♀️ 마이페이지탭, 🛠 QA

#629 🔨 [QA] 홈/마이페이지 정책 관련 QA
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/VC/HomeVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypagePostList/VC/MypagePostListVC.swift
Labels: ❤️ 정빈걸 ❤️, 🙋🏻‍♀️ 마이페이지탭, 🛠 QA, 📰 홈 탭

#624 🔨 [QA] 홈 가로스크롤 마진 수정, 홈 리로드 문제 수정
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/TVC/HomeRankingTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/TVC/HomeRecentReviewQuestionTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/VC/HomeVC.swift
Labels: 🐞 Bug, ❤️ 정빈걸 ❤️, 🛠 QA, 📰 홈 탭

#640 🔨 [FIX] 1:1 질문 상세보기 floatingBtn 띄워져있을 때 bottom Constraint값 조정하기
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/DefaultQuestionChatVC.swift
Labels: 📱 View, ✨🍕 Jieun 🐰✨, ✏️ 과방탭, ✅ Chore

#643 ✅ [CHORE] 홈 뷰 로딩 개선
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Extension/Notification.Name.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Extension/UIImageView+.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/TVC/RankingTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/VC/HomeVC.swift
Labels: 💡 Refactor, ❤️ 정빈걸 ❤️, ✅ Chore, 📰 홈 탭

#644 🔨 [FIX] 과방 메인뷰 (ReviewVC, PersonalQuestionVC) 레이아웃 충돌 이슈 대응
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/ClassroomVC.swift
Labels: 📱 View, 💡 Refactor, ⚡️ HotFix, ✨🍕 Jieun 🐰✨, ✏️ 과방탭

#645 🔨 [QA] 선배랭킹 뷰의 목록 30개까지로 제한
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/Reactor/RankingReactor.swift
Labels: 📱 View, 💜 은주 💜, ✅ Chore, 🛠 QA, 📰 홈 탭

#650 🔨 [FIX] 프로필 수정 뷰 엑세스토큰 갱신 처리
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ProfileSetting/VC/EditProfileVC.swift
Labels: 🐞 Bug, ❤️ 정빈걸 ❤️, 🙋🏻‍♀️ 마이페이지탭

#647 🔨 [QA] 내가 쓴 후기일 경우 프로필이 안보이도록
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/ReviewVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewDetailPostWithImgTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewDetailVC.swift
Labels: 💜 은주 💜, ✏️ 과방탭, 🛠 QA

#651 🔨 [FIX] 랭킹 뷰 리로드 되지 않는 문제 해결
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/Reactor/RankingReactor.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/VC/RankingVC.swift
Labels: 🐞 Bug, 📡 Network, 💜 은주 💜, 🛠 QA, 📰 홈 탭

#654 🔨 [FIX] 신고 누적자 및 부적절한 후기 작성자 권한 제한
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Class/BaseVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/ClassroomVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/VC/HomeVC.swift
Labels: 🐞 Bug, 💜 은주 💜, 🛠 QA

#655 🔨 [QA] 후기 수정 시 디폴트로 완료 버튼 비활성화
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ProfileSetting/VC/EditProfileVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewWriteVC.swift
Labels: 📱 View, 🏠 후기탭, 💜 은주 💜, ✅ Chore, 🛠 QA

#658 🔨 [FIX] 로그인 / 로그아웃시 widnow의 Root를 바꿔주도록 코드 수정
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Class/BaseVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/SignInVC.swift
Labels: 📱 View, ⚡️ HotFix, ✨🍕 Jieun 🐰✨

#664 🔨 [FIX] 홈 로딩 인디케이터 출현 시점 수정
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/MypageAPI.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/SignAPI.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/TVC/HomeRankingTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/TVC/RankingTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/VC/HomeVC.swift
Labels: 📱 View, ❤️ 정빈걸 ❤️, 📰 홈 탭

#666 🔨 [QA] 알림 작성창 나오게 수정
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Notification/VC/NotificationMainVC+TV.swift
Labels: ❤️ 정빈걸 ❤️, 🔔 알림탭, 🛠 QA

#668 🔨 [FIX] 커뮤니티 탭 학과 바텀시트 필터 적용 시 학과가 제대로 선택되지 않는 문제 해결
  NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Xib/HalfModalVC.swift
Labels: 🐞 Bug, 📱 View, ⚡️ HotFix, 💜 은주 💜, 🍉 커뮤니티탭

#671 🔨 [FIX] 권한 없는 사용자 최근 후기 리스트 진입 불가 문제 해결
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/VC/HomeVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/VC/RecentReviewVC.swift
Labels: 🐞 Bug, 📱 View, 💜 은주 💜, 🛠 QA, 📰 홈 탭

#672 🔨 [FIX] 커뮤니티 segment 이동시 communitySV의 contentOffset.y가 top으로 이동되지 않는 문제 해결
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Community/Reactor/CommunityMainReactor.swift
Labels: ✨🍕 Jieun 🐰✨, ✅ Chore, 🍉 커뮤니티탭
