Repository TeamNado-Sunbae/NadoSunbae-iOS, pull requests merged in 2022-03, with the labels that each got.

#250 🔨 [FIX] 질문가능선배 리스트 받아오는 getMajorUserList()함수 호출시점 변경
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/QuestionPersonListVC.swift
Labels: ✨🍕 Jieun 🐰✨, ✏️ 과방탭, ✅ Chore

#247 ✅ [CHORE] 후기 수정 시 학과 변경 버튼 비활성화
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewWriteVC.swift
Labels: 📱 View, 🏠 후기탭, 💜 은주 💜, ✅ Chore

#245 ✨ [FEAT] 선배 페이지 네비바 타이틀 선배 닉네임으로 적용
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC.swift
Labels: 📱 View, 🍎 Feature, 💜 은주 💜, 🙋🏻‍♀️ 마이페이지탭

#251 🔨 Fix: 이메일 유효성 검사 로직 수정 (#225)
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/SignInVC.swift
Labels: 🐞 Bug, ❤️ 정빈걸 ❤️

#253 ✨ [FEAT] 후기글 신고 기능 구현
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewDetailVC.swift
Labels: 📡 Network, 🍎 Feature, 🏠 후기탭, 💜 은주 💜

#262 ✨ [FEAT] 선배 개인페이지 학과 후기 UI 구성
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypagePostList/SB/MypageMyReviewVC.storyboard
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypagePostList/VC/MypageMyReviewVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/SB/MypageUserVC.storyboard
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC.swift
Labels: 📱 View, 🍎 Feature, 💜 은주 💜, ✏️ 과방탭

#268 ✨ [FEAT] NadoAlert case 만들기
  NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Class/NadoAlertVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Xib/NadoAlertVC.xib
Labels: 📱 View, 🍎 Feature, ❤️ 정빈걸 ❤️

#265 ✨ [FEAT] 서버에서 관리하는 url 대응
  NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Class/BaseVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/PublicAPI.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Public/AppLinkResponseModel.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/MypageSettingService.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/PublicService.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ResetPW/VC/ResetPWCompleteVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ResetPW/VC/ResetPWVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/Setting/VC/SettingAppInfoVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/Setting/VC/SettingVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/SignInVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignUp/AgreeTerms/SB/AgreeTermsVC.storyboard
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignUp/AgreeTerms/VC/AgreeTermsVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignUp/AgreeTerms/VC/TermDetailVC.swift
Labels: 📡 Network, 🍎 Feature, ❤️ 정빈걸 ❤️, 🙋🏻‍♀️ 마이페이지탭, ✅ Chore

#273 ✨ [FEAT] 과방탭 마이페이지 플로우 분기처리 및 차단 기능 구현
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/QuestionPersonListVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/SB/MypageUserVC.storyboard
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC.swift
Labels: 📡 Network, 🍎 Feature, 💜 은주 💜, ✏️ 과방탭

#271 🔨 [FIX] 정보 메인뷰 마지막 스레드 길이 버그 수정
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Info/InfoMainVC.swift
Labels: 🐞 Bug, ✨🍕 Jieun 🐰✨, ✏️ 과방탭, 🛠 QA

#276 ✨ [Feat] 로그인 뷰 디자인 변경사항 대응
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/SB/SignInSB.storyboard
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/SignInVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/logoLogin.imageset/Contents.json
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/logoLogin.imageset/logoLogin.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/logoLogin.imageset/logoLogin@2x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/logoLogin.imageset/logoLogin@3x.png
Labels: 📱 View, ❤️ 정빈걸 ❤️, ✅ Chore

#279 ✨ [FEAT] 회원가입 메일 인증 플로우
  NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/SignAPI.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Sign/ResendSignUpMailResponseModel.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Sign/SignUpDataModel.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/SignService.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ResetPW/SB/MailCompleteVC.storyboard
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ResetPW/VC/MailCompleteVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ResetPW/VC/ResetPWCompleteVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ResetPW/VC/ResetPWVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/SignInVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignUp/SignUpMajorInfo/VC/SignUpMajorInfoVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignUp/SignUpUserInfo/VC/SignUpUserInfoVC.swift
Labels: 📡 Network, 📱 View, 🍎 Feature, ❤️ 정빈걸 ❤️

#283 ✅ [CHORE] 스플래시 화면 적용
  NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/SB/SignInSB.storyboard
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/AutoSignInVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Support/AppDelegate.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/logoLogin.imageset/Contents.json
Labels: 📱 View, 💜 은주 💜, ✅ Chore

#287 ✨ [FEAT] 자동로그인 서버 변경사항 대응
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/SignAPI.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Sign/SignInDataModel.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/SignService.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/AutoSignInVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/SignInVC.swift
Labels: 📡 Network, 🍎 Feature, ❤️ 정빈걸 ❤️, ✅ Chore

#289 ✨ [FEAT] access 토큰 만료 시 처리
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Class/BaseVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/ClassroomAPI.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/MypageAPI.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/MypageSettingAPI.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/NotificationAPI.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/PublicAPI.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/ReviewAPI.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/SignAPI.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Info/InfoDetailVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Info/InfoMainVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/DefaultQuestionChatVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/EntireQuestionListVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/QuestionMainVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/QuestionPersonListVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/WriteQuestionVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/MypageMainVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypagePostList/VC/MypageMyPostListVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypagePostList/VC/MypageMyReviewVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ProfileSetting/VC/EditProfileVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ResetPW/VC/ResetPWVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/Setting/VC/BlockListVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/Setting/VC/SettingAppInfoVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/Setting/VC/SettingVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Notification/VC/NotificationMainVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewMainLinkTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewDetailVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewMainVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewWriteVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/AutoSignInVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/SignInVC.swift
Labels: 📡 Network, 🍎 Feature, ❤️ 정빈걸 ❤️

#290 ✨ [FEAT] 마이페이지 좋아요 목록 구현
  NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Struct/Identifiers.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Struct/MypageLikePostType.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/MypageAPI.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Mypage/MypageLikePostDataModel.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Mypage/MypageLikeReviewDataModel.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/MypageService.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/QuestionMain/BaseQuestionTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Info/InfoMainVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/SB/MypageSB.storyboard
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/LikeList/MypageClassroomPostListVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/LikeList/MypageLikeListSB.storyboard
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/LikeList/MypageLikeListVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/LikeList/MypageReviewLikeVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/MypageMainVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewMainPostTVC.swift
Labels: 📡 Network, 📱 View, 🍎 Feature, ✨🍕 Jieun 🐰✨, 🙋🏻‍♀️ 마이페이지탭

#294 ✨ [FEAT] 온보딩 화면 구성
  NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Extension/UIColor+.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Extension/UserDefaults+.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Global/PublicData/AppModel/OnboardingDataModel.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Onboarding/Cell/CVC/FirstOnboardingCVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Onboarding/Cell/CVC/FirstOnboardingCVC.xib
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Onboarding/Cell/CVC/OnboardingCVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Onboarding/Cell/CVC/OnboardingCVC.xib
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Onboarding/Cell/CVC/ThirdOnboardingCVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Onboarding/Cell/CVC/ThirdOnboardingCVC.xib
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Onboarding/SB/OnboardingSB.storyboard
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Onboarding/VC/OnboardingVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/SignInVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/group678.imageset/Contents.json
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/group678.imageset/group678.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/group678.imageset/group678@2x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/group678.imageset/group678@3x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/group687.imageset/Contents.json
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/group687.imageset/group687.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/group687.imageset/group687@2x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/group687.imageset/group687@3x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/group87.imageset/Contents.json
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/group87.imageset/group87.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/group87.imageset/group87@2x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/group87.imageset/group87@3x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/lastPage.imageset/Contents.json
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/lastPage.imageset/lastPage.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/lastPage.imageset/lastPage@2x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/lastPage.imageset/lastPage@3x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/thirdPage.imageset/Contents.json
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/thirdPage.imageset/thirdPage.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/thirdPage.imageset/thirdPage@2x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/thirdPage.imageset/thirdPage@3x.png
  NadoSunbae-iOS/NadoSunbae-iOS/Support/SceneDelegate.swift
Labels: 📱 View, 🍎 Feature, 💜 은주 💜

#299 🔨 [FIX] 함수명 관련 에러 수정
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/SignInVC.swift
Labels: ⚡️ HotFix, ❤️ 정빈걸 ❤️

#306 🔨 [FIX] 후기 상세 뷰 프로필 관련 QA 및 수정사항 대응
  NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewDetailGrayTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewDetailGrayTVC.xib
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewDetailProfileTVC.xib
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/SB/ReviewDetailSB.storyboard
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewDetailVC.swift
Labels: 📱 View, 💜 은주 💜, ✅ Chore, 🛠 QA

#307 🔨 [FIX] 자동로그인, accessToken 갱신 에러 해결
  NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Class/BaseVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Global/PublicData/Singleton/UserToken.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/MypageAPI.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/ClassroomService.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/MypageService.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/MypageSettingService.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/NotificationService.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/PublicService.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/ReviewService.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/SignService.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/QuestionMainVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/MypageMainVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/AutoSignInVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/SignInVC.swift
Labels: ⚡️ HotFix, ❤️ 정빈걸 ❤️

#310 ✨ [FEAT] 업데이트 확인 알럿창 심기
  NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Class/BaseVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Global/PublicData/Singleton/AppVersion.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/Setting/Cell/SettingVersionTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/Setting/VC/SettingAppInfoVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewMainVC.swift
Labels: 📡 Network, 📱 View, 🍎 Feature, ❤️ 정빈걸 ❤️

#311 ✨ [FEAT] 스플래시 fade 효과 적용
  NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Extension/UIView+.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/SB/SignInSB.storyboard
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/AutoSignInVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Support/AppDelegate.swift
Labels: 📱 View, 🍎 Feature, 💜 은주 💜

#316 ✅ [CHORE] 학과 리스트 바텀 시트 UI 수정
  NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Xib/MajorTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Xib/MajorTVC.xib
Labels: 📱 View, 🏠 후기탭, 💜 은주 💜, ✅ Chore

#314 🔨 [FIX] 액세스토큰 갱신 시 싱글톤에 잘못 저장하는 버그 수정
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Class/BaseVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/MypageAPI.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/NotificationService.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/LikeList/MypageReviewLikeVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/MypageMainVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Notification/VC/NotificationMainVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewMainVC.swift
Labels: ⚡️ HotFix, ❤️ 정빈걸 ❤️

#320 🔨 [FIX] 탈퇴 알럿 QA 대응
  NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Class/NadoAlertVC.swift
Labels: ❤️ 정빈걸 ❤️, 🙋🏻‍♀️ 마이페이지탭, 🛠 QA

#318 🔨 [FIX] 프로필 수정 QA 대응
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/MypageMainVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ProfileSetting/SB/EditProfileVC.storyboard
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ProfileSetting/VC/EditProfileVC.swift
Labels: ❤️ 정빈걸 ❤️, 🙋🏻‍♀️ 마이페이지탭, 🛠 QA

#327 🔨 [FIX] 로그인 QA 대응
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/SignInVC.swift
Labels: ❤️ 정빈걸 ❤️, 🛠 QA

#325 🔨 [FIX] 과방 메인 전체에게 질문 TableView Height 버그 해결
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/QuestionMainVC.swift
Labels: 📱 View, ⚡️ HotFix, ✨🍕 Jieun 🐰✨, ✏️ 과방탭, 🛠 QA

#329 🔨 [FIX] 알림탭에서 삭제된 게시글의 알림을 누를 경우 오류 해결
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Class/BaseVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Xib/NadoAlertVC.xib
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/ClassroomAPI.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/InfoDetail/InfoQuestionTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Info/InfoDetailVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/DefaultQuestionChatVC.swift
Labels: 📡 Network, ⚡️ HotFix, ✨🍕 Jieun 🐰✨, ✏️ 과방탭, 🔔 알림탭, 🛠 QA

#331 🔨 [FIX] 회원가입 QA 대응
  NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignUp/SignUpMajorInfo/VC/SelectMajorModalVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignUp/SignUpUserInfo/SB/SignUpUserInfoVC.storyboard
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignUp/SignUpUserInfo/VC/SignUpUserInfoVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Support/Info.plist
Labels: ❤️ 정빈걸 ❤️, 🛠 QA

#334 🔨 [FIX] 알림탭에서 글로 이동 시 정확한 글로 이동하지 않는 문제 수정
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Notification/VC/NotificationMainVC+TV.swift
Labels: 🐞 Bug, ❤️ 정빈걸 ❤️, 🔔 알림탭, 🛠 QA

#342 🔨 [FIX] 온보딩 전에 스플래시 뜨지 않는 문제 해결
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/AutoSignInVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Support/SceneDelegate.swift
Labels: 📱 View, 💜 은주 💜, ✅ Chore

#348 ✅ [CHORE] 후기 작성 뷰 글자수 세기
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/SB/ReviewWriteSB.storyboard
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewMainVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewWriteVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Xib/FilterVC.xib
Labels: 📱 View, 🏠 후기탭, 💜 은주 💜, ✅ Chore

#352 🔨 [FIX] 회원가입 전공 선택 미진입 선택 오류
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignUp/SignUpMajorInfo/VC/SignUpMajorInfoVC.swift
Labels: ❤️ 정빈걸 ❤️, 🛠 QA

#354 🔨 [FIX] 후기글 수정 시 이전 작성 글 글자수 표시되지 않는 문제 해결
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewWriteVC.swift
Labels: 🐞 Bug, 📱 View, 🏠 후기탭, 💜 은주 💜, ✅ Chore

#355 ✨ [FEAT] 신고 당한 유저, 부적절 후기 작성 유저 권한 처리
  NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj
  NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/xcshareddata/xcschemes/NadoSunbae-iOS.xcscheme
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Class/BaseVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Extension/UserDefaults+.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Global/PublicData/Singleton/UserPermissionInfo.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Struct/PermissionType.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Sign/SignInDataModel.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Info/InfoDetailVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Info/InfoMainVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/DefaultQuestionChatVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/EntireQuestionListVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/QuestionMainVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/QuestionPersonListVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/LikeList/MypageClassroomPostListVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/LikeList/MypageReviewLikeVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/MypageMainVC+TV.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypagePostList/VC/MypageMyPostListVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypagePostList/VC/MypageMyReviewVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC+TV.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ResetPW/VC/ResetPWVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/Setting/VC/SettingVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Notification/VC/NotificationMainVC+TV.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Onboarding/VC/OnboardingVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewDetailVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewMainVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewWriteVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/AutoSignInVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/SignInVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignUp/AgreeTerms/VC/AgreeTermsVC.swift
Labels: 🍎 Feature, 💡 Refactor, 🏠 후기탭, ⚡️ HotFix, ✨🍕 Jieun 🐰✨, ✏️ 과방탭, 🙋🏻‍♀️ 마이페이지탭, 🔔 알림탭

#358 🔨 [FIX] 질문, 정보 작성뷰 textView 자동완성 기능 제거하기
  NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Class/NadoTextView.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/WriteQuestionVC.swift
Labels: ✨🍕 Jieun 🐰✨, ✏️ 과방탭, ✅ Chore, 🛠 QA

#359 🔨 [FIX] 마이페이지 내가 쓴 후기 마지막 하나 삭제했을 때 바로 반영되지 않는 문제 해결
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewDetailVC.swift
Labels: 💜 은주 💜, 🙋🏻‍♀️ 마이페이지탭, ✅ Chore, 🛠 QA

#363 🔨 [FIX] 비밀번호 찾기 메일 전송 화면 이미지 수정
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ResetPW/SB/MailCompleteVC.storyboard
Labels: 🐞 Bug, ❤️ 정빈걸 ❤️, 🛠 QA
