Repository TeamNado-Sunbae/NadoSunbae-iOS, pull requests merged in 2022-11, with the labels that each got.

#685 ✨ [FEAT] 홈, 마이페이지, 회원가입 관련 GA 이벤트 수집 기능 구현
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Class/BaseTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/TVC/HomeBannerTVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Home/VC/HomeVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ProfileSetting/VC/EditProfileVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ResetPW/VC/MailCompleteVC.swift
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/Setting/VC/NotificationSettingVC.swift
Labels: 🍎 Feature, ❤️ 정빈걸 ❤️, 🙋🏻‍♀️ 마이페이지탭, 📰 홈 탭

#689 🔨 [FIX] 업데이트 알럿 무한 로딩 버그 해결
  NadoSunbae-iOS/NadoSunbae-iOS/Global/Class/BaseVC.swift
Labels: ⚡️ HotFix, ❤️ 정빈걸 ❤️

#695 🔨 [FIX] 과방 최신 1:1질문 TV, 우리과 선배찾기 CV Empty 상태일 때도 클릭되는 문제 해결
  NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/PersonalQuestionVC.swift
Labels: ✨🍕 Jieun 🐰✨, ✏️ 과방탭, ✅ Chore

#698 🔨 [FIX] 과방 바텀시트 즐겨찾기 추가 시 바로 반영이 되지 않는 문제
  NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Xib/HalfModalVC.swift
Labels: 🐞 Bug, 💜 은주 💜, ✏️ 과방탭, ✅ Chore
